import '@/styles/global.css'
import { Inter, Squada_One, Source_Code_Pro } from "next/font/google"
import { cn } from '@/lib/utils'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { Toaster } from '@/ui/toast'
import Providers from '@/components/Providers'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

const squada_one = Squada_One({
  subsets: ['latin'],
  variable: '--font-display',
  weight: '400',
})

const source_code_pro = Source_Code_Pro({
  subsets: ['latin'],
  variable: '--font-mono',
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <title>Kristian Wobbes</title>
        <meta charSet='UTF-8' />
        <meta httpEquiv='X-UA-Compatible' content='IE=edge' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta name='description' content='portfolio for Kristian Wobbes' />
        <link rel='apple-touch-icon' sizes='180x180' href='/favicon/apple-touch-icon.png' />
        <link rel='icon' type='image/png' sizes='32x32' href='/favicon/favicon-32x32.png' />
        <link rel='icon' type='image/png' sizes='16x16' href='/favicon/favicon-16x16.png' />
        <link rel='manifest' href='/favicon/site.webmanifest' />
        <link rel='mask-icon' href='/favicon/safari-pinned-tab.svg' color='#0f172a' />
        <link rel='shortcut icon' href='/favicon/favicon.ico' />
        <meta name='msapplication-TileColor' content='#603cba' />
        <meta name='msapplication-config' content='/favicon/browserconfig.xml' />
        <meta name='theme-color' content='#f8f9fc' />
      </head>
      <body
        className={cn('bg-slate-50 dark:bg-slate-900 antialiased relative', `${inter.variable} ${source_code_pro.variable} ${squada_one.variable}`)}
      >
        <Providers>
          <Toaster position='bottom-right' />
          <Header />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
/* 
import { cn } from '@/lib/utils';
import '@/styles/globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Providers from '@/components/Providers';
import MobileMenu from '@/components/MobileMenu';
import { Toaster } from '@/ui/toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Vardal botsystem',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn('bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-white antialiased', inter.className)}>
        <Providers>
          <Toaster position='bottom-right' />
          <MobileMenu />
          <header>
            <Navbar />
          </header>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}

*/
